TRUNCATE TABLE sticker_catalog CASCADE;
INSERT INTO sticker_catalog (number,player_name,team,section,sticker_type,image_url) VALUES
('001','Trofeo FIFA','Introducción','Introducción','special',NULL),
('002','Balón Oficial','Introducción','Introducción','special',NULL),
('003','Logo FIFA World Cup 2026','Introducción','Introducción','special',NULL),
('004','Mascota Maple','Introducción','Introducción','special',NULL),
('005','Mascota Clutch','Introducción','Introducción','special',NULL),
('006','Mascota Zavu','Introducción','Introducción','special',NULL),
('007','Estadio MetLife (USA)','Introducción','Introducción','special',NULL),
('008','Estadio Azteca (MEX)','Introducción','Introducción','special',NULL),
('009','Estadio Rose Bowl (USA)','Introducción','Introducción','special',NULL),
('010','Estadio BC Place (CAN)','Introducción','Introducción','special',NULL),
('011','Estadio SoFi (USA)','Introducción','Introducción','special',NULL),
('012','Estadio BMO Field (CAN)','Introducción','Introducción','special',NULL),
('013','Estadio AT&T (USA)','Introducción','Introducción','special',NULL),
('014','Estadio Levi''s (USA)','Introducción','Introducción','special',NULL),
('015','Estadio Arrowhead (USA)','Introducción','Introducción','special',NULL),
('016','Estadio Gillette (USA)','Introducción','Introducción','special',NULL),
('017','Estadio Lincoln Financial (USA)','Introducción','Introducción','special',NULL),
('018','Los Tres Países Anfitriones','Introducción','Introducción','special',NULL),
('019','El Grupo A','Introducción','Introducción','special',NULL),
('020','El Camino al Título','Introducción','Introducción','special',NULL),
('021','Escudo Oficial','Algeria','Algeria','badge',NULL),
('022','Foto del Equipo','Algeria','Algeria','logo',NULL),
('023','Rayan Aït-Nouri','Algeria','Algeria','player',NULL),
('024','Islam Slimani','Algeria','Algeria','player',NULL),
('025','Rami Bensebaïni','Algeria','Algeria','player',NULL),
('026','Youcef Atal','Algeria','Algeria','player',NULL),
('027','Aïssa Mandi','Algeria','Algeria','player',NULL),
('028','Alexis Guendouz','Algeria','Algeria','player',NULL),
('029','Hichem Boudaoui','Algeria','Algeria','player',NULL),
('030','Nabil Bentaleb','Algeria','Algeria','player',NULL),
('031','Yacine Adli','Algeria','Algeria','player',NULL),
('032','Farès Chaïbi','Algeria','Algeria','player',NULL),
('033','Billal Brahimi','Algeria','Algeria','player',NULL),
('034','Saïd Benrahma','Algeria','Algeria','player',NULL),
('035','Amine Gouiri','Algeria','Algeria','player',NULL),
('036','Mohammed Amoura','Algeria','Algeria','player',NULL),
('037','Riyad Mahrez','Algeria','Algeria','player',NULL),
('038','Baghdad Bounedjah','Algeria','Algeria','player',NULL),
('039','Escudo Oficial','Argentina','Argentina','badge',NULL),
('040','Foto del Equipo','Argentina','Argentina','logo',NULL),
('041','Emiliano Martínez','Argentina','Argentina','player',NULL),
('042','Geronimo Rulli','Argentina','Argentina','player',NULL),
('043','Nahuel Molina','Argentina','Argentina','player',NULL),
('044','Cristian Romero','Argentina','Argentina','player',NULL),
('045','Nicolás Otamendi','Argentina','Argentina','player',NULL),
('046','Nicolás González','Argentina','Argentina','player',NULL),
('047','Exequiel Palacios','Argentina','Argentina','player',NULL),
('048','Enzo Fernández','Argentina','Argentina','player',NULL),
('049','Alexis Mac Allister','Argentina','Argentina','player',NULL),
('050','Rodrigo De Paul','Argentina','Argentina','player',NULL),
('051','Giovanni Lo Celso','Argentina','Argentina','player',NULL),
('052','Giuliano Simeone','Argentina','Argentina','player',NULL),
('053','Julián Álvarez','Argentina','Argentina','player',NULL),
('054','Lautaro Martínez','Argentina','Argentina','player',NULL),
('055','Franco Mastantuono','Argentina','Argentina','player',NULL),
('056','Lionel Messi','Argentina','Argentina','player',NULL),
('057','Escudo Oficial','Australia','Australia','badge',NULL),
('058','Foto del Equipo','Australia','Australia','logo',NULL),
('059','Mathew Ryan','Australia','Australia','player',NULL),
('060','Danny Vukovic','Australia','Australia','player',NULL),
('061','Harry Souttar','Australia','Australia','player',NULL),
('062','Alessandro Circati','Australia','Australia','player',NULL),
('063','Miloš Degenek','Australia','Australia','player',NULL),
('064','Nathaniel Atkinson','Australia','Australia','player',NULL),
('065','Aziz Behich','Australia','Australia','player',NULL),
('066','Jackson Irvine','Australia','Australia','player',NULL),
('067','Riley McGree','Australia','Australia','player',NULL),
('068','Cameron Devlin','Australia','Australia','player',NULL),
('069','Aiden O''Neill','Australia','Australia','player',NULL),
('070','Connor Metcalfe','Australia','Australia','player',NULL),
('071','Craig Goodwin','Australia','Australia','player',NULL),
('072','Nestory Irankunda','Australia','Australia','player',NULL),
('073','Jordan Bos','Australia','Australia','player',NULL),
('074','Lewis Miller','Australia','Australia','player',NULL),
('075','Escudo Oficial','Austria','Austria','badge',NULL),
('076','Foto del Equipo','Austria','Austria','logo',NULL),
('077','Alexander Schlager','Austria','Austria','player',NULL),
('078','Patrick Pentz','Austria','Austria','player',NULL),
('079','Kevin Danso','Austria','Austria','player',NULL),
('080','Philipp Lienhart','Austria','Austria','player',NULL),
('081','David Alaba','Austria','Austria','player',NULL),
('082','Stefan Posch','Austria','Austria','player',NULL),
('083','Valentino Lazaro','Austria','Austria','player',NULL),
('084','Konrad Laimer','Austria','Austria','player',NULL),
('085','Nicolas Seiwald','Austria','Austria','player',NULL),
('086','Marcel Sabitzer','Austria','Austria','player',NULL),
('087','Florian Grillitsch','Austria','Austria','player',NULL),
('088','Romano Schmid','Austria','Austria','player',NULL),
('089','Christoph Baumgartner','Austria','Austria','player',NULL),
('090','Andreas Weimann','Austria','Austria','player',NULL),
('091','Marko Arnautović','Austria','Austria','player',NULL),
('092','Michael Gregoritsch','Austria','Austria','player',NULL),
('093','Escudo Oficial','Belgium','Belgium','badge',NULL),
('094','Foto del Equipo','Belgium','Belgium','logo',NULL),
('095','Thibaut Courtois','Belgium','Belgium','player',NULL),
('096','Koen Casteels','Belgium','Belgium','player',NULL),
('097','Timothy Castagne','Belgium','Belgium','player',NULL),
('098','Wout Faes','Belgium','Belgium','player',NULL),
('099','Arthur Theate','Belgium','Belgium','player',NULL),
('100','Jan Vertonghen','Belgium','Belgium','player',NULL),
('101','Maxime De Cuyper','Belgium','Belgium','player',NULL),
('102','Amadou Onana','Belgium','Belgium','player',NULL),
('103','Youri Tielemans','Belgium','Belgium','player',NULL),
('104','Kevin De Bruyne','Belgium','Belgium','player',NULL),
('105','Johan Bakayoko','Belgium','Belgium','player',NULL),
('106','Jérémy Doku','Belgium','Belgium','player',NULL),
('107','Charles De Ketelaere','Belgium','Belgium','player',NULL),
('108','Leandro Trossard','Belgium','Belgium','player',NULL),
('109','Lois Openda','Belgium','Belgium','player',NULL),
('110','Romelu Lukaku','Belgium','Belgium','player',NULL),
('111','Escudo Oficial','Brazil','Brazil','badge',NULL),
('112','Foto del Equipo','Brazil','Brazil','logo',NULL),
('113','Alisson','Brazil','Brazil','player',NULL),
('114','Ederson','Brazil','Brazil','player',NULL),
('115','Danilo','Brazil','Brazil','player',NULL),
('116','Éder Militão','Brazil','Brazil','player',NULL),
('117','Gabriel Magalhães','Brazil','Brazil','player',NULL),
('118','Marquinhos','Brazil','Brazil','player',NULL),
('119','Renan Lodi','Brazil','Brazil','player',NULL),
('120','Casemiro','Brazil','Brazil','player',NULL),
('121','Bruno Guimarães','Brazil','Brazil','player',NULL),
('122','Lucas Paquetá','Brazil','Brazil','player',NULL),
('123','Rodrygo','Brazil','Brazil','player',NULL),
('124','Raphinha','Brazil','Brazil','player',NULL),
('125','Vinícius Júnior','Brazil','Brazil','player',NULL),
('126','Matheus Cunha','Brazil','Brazil','player',NULL),
('127','Endrick','Brazil','Brazil','player',NULL),
('128','Estêvão','Brazil','Brazil','player',NULL),
('129','Escudo Oficial','Canada','Canada','badge',NULL),
('130','Foto del Equipo','Canada','Canada','logo',NULL),
('131','Dayne St. Clair','Canada','Canada','player',NULL),
('132','Milan Borjan','Canada','Canada','player',NULL),
('133','Richie Laryea','Canada','Canada','player',NULL),
('134','Derek Cornelius','Canada','Canada','player',NULL),
('135','Alistair Johnston','Canada','Canada','player',NULL),
('136','Scott Kennedy','Canada','Canada','player',NULL),
('137','Alphonso Davies','Canada','Canada','player',NULL),
('138','Stephen Eustáquio','Canada','Canada','player',NULL),
('139','Ismaël Koné','Canada','Canada','player',NULL),
('140','Jonathan Osorio','Canada','Canada','player',NULL),
('141','Liam Millar','Canada','Canada','player',NULL),
('142','Jacob Shaffelburg','Canada','Canada','player',NULL),
('143','Tajon Buchanan','Canada','Canada','player',NULL),
('144','Jonathan David','Canada','Canada','player',NULL),
('145','Cyle Larin','Canada','Canada','player',NULL),
('146','Jacen Russell-Rowe','Canada','Canada','player',NULL),
('147','Escudo Oficial','Cape Verde','Cape Verde','badge',NULL),
('148','Foto del Equipo','Cape Verde','Cape Verde','logo',NULL),
('149','Vozinha','Cape Verde','Cape Verde','player',NULL),
('150','Marcelo Djalo','Cape Verde','Cape Verde','player',NULL),
('151','Logan Costa','Cape Verde','Cape Verde','player',NULL),
('152','Steven Moreira','Cape Verde','Cape Verde','player',NULL),
('153','Pico','Cape Verde','Cape Verde','player',NULL),
('154','João Paulo','Cape Verde','Cape Verde','player',NULL),
('155','Marco Soares','Cape Verde','Cape Verde','player',NULL),
('156','Bryan Tavares','Cape Verde','Cape Verde','player',NULL),
('157','Kevin Pina','Cape Verde','Cape Verde','player',NULL),
('158','Jamiro Monteiro','Cape Verde','Cape Verde','player',NULL),
('159','Patrick Andrade','Cape Verde','Cape Verde','player',NULL),
('160','Yannick Semedo','Cape Verde','Cape Verde','player',NULL),
('161','Ryan Mendes','Cape Verde','Cape Verde','player',NULL),
('162','Jovane Cabral','Cape Verde','Cape Verde','player',NULL),
('163','Julio Tavares','Cape Verde','Cape Verde','player',NULL),
('164','Daílson Livramento','Cape Verde','Cape Verde','player',NULL),
('165','Escudo Oficial','Colombia','Colombia','badge',NULL),
('166','Foto del Equipo','Colombia','Colombia','logo',NULL),
('167','Camilo Vargas','Colombia','Colombia','player',NULL),
('168','David Ospina','Colombia','Colombia','player',NULL),
('169','Dávinson Sánchez','Colombia','Colombia','player',NULL),
('170','Yerry Mina','Colombia','Colombia','player',NULL),
('171','Daniel Muñoz','Colombia','Colombia','player',NULL),
('172','Wilmar Barrios','Colombia','Colombia','player',NULL),
('173','Jefferson Lerma','Colombia','Colombia','player',NULL),
('174','Richard Ríos','Colombia','Colombia','player',NULL),
('175','James Rodríguez','Colombia','Colombia','player',NULL),
('176','Juan Fernando Quintero','Colombia','Colombia','player',NULL),
('177','Jhon Arias','Colombia','Colombia','player',NULL),
('178','Luis Díaz','Colombia','Colombia','player',NULL),
('179','Cucho Hernández','Colombia','Colombia','player',NULL),
('180','Rafael Santos Borré','Colombia','Colombia','player',NULL),
('181','Jhon Jáder Durán','Colombia','Colombia','player',NULL),
('182','Luis Suárez','Colombia','Colombia','player',NULL),
('183','Escudo Oficial','Croatia','Croatia','badge',NULL),
('184','Foto del Equipo','Croatia','Croatia','logo',NULL),
('185','Dominik Livaković','Croatia','Croatia','player',NULL),
('186','Ivica Ivušić','Croatia','Croatia','player',NULL),
('187','Duje Ćaleta-Car','Croatia','Croatia','player',NULL),
('188','Joško Gvardiol','Croatia','Croatia','player',NULL),
('189','Josip Stanišić','Croatia','Croatia','player',NULL),
('190','Borna Sosa','Croatia','Croatia','player',NULL),
('191','Luka Ivanušec','Croatia','Croatia','player',NULL),
('192','Mateo Kovačić','Croatia','Croatia','player',NULL),
('193','Luka Modrić','Croatia','Croatia','player',NULL),
('194','Lovro Majer','Croatia','Croatia','player',NULL),
('195','Mario Pašalić','Croatia','Croatia','player',NULL),
('196','Petar Sucić','Croatia','Croatia','player',NULL),
('197','Ivan Perišić','Croatia','Croatia','player',NULL),
('198','Andrej Kramarić','Croatia','Croatia','player',NULL),
('199','Ante Budimir','Croatia','Croatia','player',NULL),
('200','Bruno Petković','Croatia','Croatia','player',NULL),
('201','Escudo Oficial','Curaçao','Curaçao','badge',NULL),
('202','Foto del Equipo','Curaçao','Curaçao','logo',NULL),
('203','Eloy Room','Curaçao','Curaçao','player',NULL),
('204','Giliano Wijnaldum','Curaçao','Curaçao','player',NULL),
('205','Sherel Floranus','Curaçao','Curaçao','player',NULL),
('206','Roshon van Eijma','Curaçao','Curaçao','player',NULL),
('207','Armando Obispo','Curaçao','Curaçao','player',NULL),
('208','Cuco Martina','Curaçao','Curaçao','player',NULL),
('209','Liviano Comenica','Curaçao','Curaçao','player',NULL),
('210','Juriën Gaari','Curaçao','Curaçao','player',NULL),
('211','Juninho Bacuna','Curaçao','Curaçao','player',NULL),
('212','Kenló Gorré','Curaçao','Curaçao','player',NULL),
('213','Glen Kamara','Curaçao','Curaçao','player',NULL),
('214','Raphael Obinna','Curaçao','Curaçao','player',NULL),
('215','Leandro Bacuna','Curaçao','Curaçao','player',NULL),
('216','Sontje Hansen','Curaçao','Curaçao','player',NULL),
('217','Myron Boadu','Curaçao','Curaçao','player',NULL),
('218','Jearl Margaritha','Curaçao','Curaçao','player',NULL),
('219','Escudo Oficial','Denmark','Denmark','badge',NULL),
('220','Foto del Equipo','Denmark','Denmark','logo',NULL),
('221','Kasper Schmeichel','Denmark','Denmark','player',NULL),
('222','Oliver Christensen','Denmark','Denmark','player',NULL),
('223','Simon Kjær','Denmark','Denmark','player',NULL),
('224','Andreas Christensen','Denmark','Denmark','player',NULL),
('225','Jannik Vestergaard','Denmark','Denmark','player',NULL),
('226','Joakim Mæhle','Denmark','Denmark','player',NULL),
('227','Thomas Delaney','Denmark','Denmark','player',NULL),
('228','Pierre-Emile Højbjerg','Denmark','Denmark','player',NULL),
('229','Morten Hjulmand','Denmark','Denmark','player',NULL),
('230','Christian Eriksen','Denmark','Denmark','player',NULL),
('231','Viktor Claesson','Denmark','Denmark','player',NULL),
('232','Andreas Skov Olsen','Denmark','Denmark','player',NULL),
('233','Mikkel Damsgaard','Denmark','Denmark','player',NULL),
('234','Kasper Dolberg','Denmark','Denmark','player',NULL),
('235','Rasmus Højlund','Denmark','Denmark','player',NULL),
('236','Martin Braithwaite','Denmark','Denmark','player',NULL),
('237','Escudo Oficial','Ecuador','Ecuador','badge',NULL),
('238','Foto del Equipo','Ecuador','Ecuador','logo',NULL),
('239','Hernán Galíndez','Ecuador','Ecuador','player',NULL),
('240','Alexander Domínguez','Ecuador','Ecuador','player',NULL),
('241','Piero Hincapié','Ecuador','Ecuador','player',NULL),
('242','Pervis Estupiñán','Ecuador','Ecuador','player',NULL),
('243','Willian Pacho','Ecuador','Ecuador','player',NULL),
('244','Robert Arboleda','Ecuador','Ecuador','player',NULL),
('245','Ángelo Preciado','Ecuador','Ecuador','player',NULL),
('246','Moisés Caicedo','Ecuador','Ecuador','player',NULL),
('247','Alan Franco','Ecuador','Ecuador','player',NULL),
('248','Joel Ordóñez','Ecuador','Ecuador','player',NULL),
('249','Jhegson Méndez','Ecuador','Ecuador','player',NULL),
('250','Jeremy Sarmiento','Ecuador','Ecuador','player',NULL),
('251','Gonzalo Plata','Ecuador','Ecuador','player',NULL),
('252','Kendry Páez','Ecuador','Ecuador','player',NULL),
('253','Kevin Rodríguez','Ecuador','Ecuador','player',NULL),
('254','Enner Valencia','Ecuador','Ecuador','player',NULL),
('255','Escudo Oficial','Egypt','Egypt','badge',NULL),
('256','Foto del Equipo','Egypt','Egypt','logo',NULL),
('257','Mohamed El-Shenawy','Egypt','Egypt','player',NULL),
('258','Ahmed El-Shenawy','Egypt','Egypt','player',NULL),
('259','Mohamed Hany','Egypt','Egypt','player',NULL),
('260','Ahmed Hegazy','Egypt','Egypt','player',NULL),
('261','Mohamed Abdelmonem','Egypt','Egypt','player',NULL),
('262','Ayman Ashraf','Egypt','Egypt','player',NULL),
('263','Ramy Rabia','Egypt','Egypt','player',NULL),
('264','Marwan Attia','Egypt','Egypt','player',NULL),
('265','Zizo','Egypt','Egypt','player',NULL),
('266','Amr El-Sulaya','Egypt','Egypt','player',NULL),
('267','Hamdy Fathy','Egypt','Egypt','player',NULL),
('268','Omar El-Abd','Egypt','Egypt','player',NULL),
('269','Mostafa Mohamed','Egypt','Egypt','player',NULL),
('270','Trézéguet','Egypt','Egypt','player',NULL),
('271','Omar Marmoush','Egypt','Egypt','player',NULL),
('272','Mohamed Salah','Egypt','Egypt','player',NULL),
('273','Escudo Oficial','England','England','badge',NULL),
('274','Foto del Equipo','England','England','logo',NULL),
('275','Jordan Pickford','England','England','player',NULL),
('276','Aaron Ramsdale','England','England','player',NULL),
('277','Reece James','England','England','player',NULL),
('278','Trent Alexander-Arnold','England','England','player',NULL),
('279','John Stones','England','England','player',NULL),
('280','Ben White','England','England','player',NULL),
('281','Declan Rice','England','England','player',NULL),
('282','Jordan Henderson','England','England','player',NULL),
('283','Conor Gallagher','England','England','player',NULL),
('284','Phil Foden','England','England','player',NULL),
('285','Bukayo Saka','England','England','player',NULL),
('286','Cole Palmer','England','England','player',NULL),
('287','Jude Bellingham','England','England','player',NULL),
('288','Marcus Rashford','England','England','player',NULL),
('289','Ollie Watkins','England','England','player',NULL),
('290','Harry Kane','England','England','player',NULL),
('291','Escudo Oficial','France','France','badge',NULL),
('292','Foto del Equipo','France','France','logo',NULL),
('293','Mike Maignan','France','France','player',NULL),
('294','Alphonse Areola','France','France','player',NULL),
('295','William Saliba','France','France','player',NULL),
('296','Jules Koundé','France','France','player',NULL),
('297','Benjamin Pavard','France','France','player',NULL),
('298','Lucas Hernández','France','France','player',NULL),
('299','Théo Hernández','France','France','player',NULL),
('300','Aurélien Tchouaméni','France','France','player',NULL),
('301','Eduardo Camavinga','France','France','player',NULL),
('302','Antoine Griezmann','France','France','player',NULL),
('303','Bradley Barcola','France','France','player',NULL),
('304','Ousmane Dembélé','France','France','player',NULL),
('305','Desire Doué','France','France','player',NULL),
('306','Marcus Thuram','France','France','player',NULL),
('307','Randal Kolo Muani','France','France','player',NULL),
('308','Kylian Mbappé','France','France','player',NULL),
('309','Escudo Oficial','Germany','Germany','badge',NULL),
('310','Foto del Equipo','Germany','Germany','logo',NULL),
('311','Marc-André ter Stegen','Germany','Germany','player',NULL),
('312','Oliver Baumann','Germany','Germany','player',NULL),
('313','Antonio Rüdiger','Germany','Germany','player',NULL),
('314','Jonathan Tah','Germany','Germany','player',NULL),
('315','Robin Koch','Germany','Germany','player',NULL),
('316','Felix Nmecha','Germany','Germany','player',NULL),
('317','Toni Kroos','Germany','Germany','player',NULL),
('318','Joshua Kimmich','Germany','Germany','player',NULL),
('319','Leon Goretzka','Germany','Germany','player',NULL),
('320','Florian Wirtz','Germany','Germany','player',NULL),
('321','Jamal Musiala','Germany','Germany','player',NULL),
('322','Serge Gnabry','Germany','Germany','player',NULL),
('323','Thomas Müller','Germany','Germany','player',NULL),
('324','Leroy Sané','Germany','Germany','player',NULL),
('325','Kai Havertz','Germany','Germany','player',NULL),
('326','Niclas Füllkrug','Germany','Germany','player',NULL),
('327','Escudo Oficial','Ghana','Ghana','badge',NULL),
('328','Foto del Equipo','Ghana','Ghana','logo',NULL),
('329','Lawrence Ati Zigi','Ghana','Ghana','player',NULL),
('330','Abdul Manaf Nurudeen','Ghana','Ghana','player',NULL),
('331','Alidu Seidu','Ghana','Ghana','player',NULL),
('332','Alexander Djiku','Ghana','Ghana','player',NULL),
('333','Tariq Lamptey','Ghana','Ghana','player',NULL),
('334','Baba Rahman','Ghana','Ghana','player',NULL),
('335','Gideon Mensah','Ghana','Ghana','player',NULL),
('336','Thomas Partey','Ghana','Ghana','player',NULL),
('337','Mohammed Kudus','Ghana','Ghana','player',NULL),
('338','Daniel-Kofi Kyereh','Ghana','Ghana','player',NULL),
('339','Caleb Ekuban','Ghana','Ghana','player',NULL),
('340','Abdul Fatawu Issahaku','Ghana','Ghana','player',NULL),
('341','Kamaldeen Sulemana','Ghana','Ghana','player',NULL),
('342','Inaki Williams','Ghana','Ghana','player',NULL),
('343','Jordan Ayew','Ghana','Ghana','player',NULL),
('344','Antoine Semenyo','Ghana','Ghana','player',NULL),
('345','Escudo Oficial','Haiti','Haiti','badge',NULL),
('346','Foto del Equipo','Haiti','Haiti','logo',NULL),
('347','Johnny Placide','Haiti','Haiti','player',NULL),
('348','Melchie Dumornay','Haiti','Haiti','player',NULL),
('349','Ricardo Adé','Haiti','Haiti','player',NULL),
('350','Carlens Arcus','Haiti','Haiti','player',NULL),
('351','Hannes Delcroix','Haiti','Haiti','player',NULL),
('352','Jessé Saint-Just','Haiti','Haiti','player',NULL),
('353','Leverton Pierre','Haiti','Haiti','player',NULL),
('354','Danley Jean-Jacques','Haiti','Haiti','player',NULL),
('355','Jean-Aéner Bellegarde','Haiti','Haiti','player',NULL),
('356','Garry Rodrigues','Haiti','Haiti','player',NULL),
('357','Gregory Bourgeois','Haiti','Haiti','player',NULL),
('358','Ruben Providence','Haiti','Haiti','player',NULL),
('359','Steeven Saba','Haiti','Haiti','player',NULL),
('360','Duckens Nazon','Haiti','Haiti','player',NULL),
('361','Don Deedon Loucius','Haiti','Haiti','player',NULL),
('362','Frantzdy Pierrot','Haiti','Haiti','player',NULL),
('363','Escudo Oficial','Iran','Iran','badge',NULL),
('364','Foto del Equipo','Iran','Iran','logo',NULL),
('365','Alireza Beiranvand','Iran','Iran','player',NULL),
('366','Hossein Hosseini','Iran','Iran','player',NULL),
('367','Shoja Khalilzadeh','Iran','Iran','player',NULL),
('368','Morteza Pouraliganji','Iran','Iran','player',NULL),
('369','Milad Mohammadi','Iran','Iran','player',NULL),
('370','Sadegh Moharrami','Iran','Iran','player',NULL),
('371','Ramin Rezaeian','Iran','Iran','player',NULL),
('372','Saeid Ezatolahi','Iran','Iran','player',NULL),
('373','Hossein Kanani','Iran','Iran','player',NULL),
('374','Ahmad Nourollahi','Iran','Iran','player',NULL),
('375','Saman Ghoddos','Iran','Iran','player',NULL),
('376','Ali Gholizadeh','Iran','Iran','player',NULL),
('377','Mohammad Mohebi','Iran','Iran','player',NULL),
('378','Alireza Jahanbakhsh','Iran','Iran','player',NULL),
('379','Sardar Azmoun','Iran','Iran','player',NULL),
('380','Mehdi Taremi','Iran','Iran','player',NULL),
('381','Escudo Oficial','Italy','Italy','badge',NULL),
('382','Foto del Equipo','Italy','Italy','logo',NULL),
('383','Gianluigi Donnarumma','Italy','Italy','player',NULL),
('384','Alex Meret','Italy','Italy','player',NULL),
('385','Giovanni Di Lorenzo','Italy','Italy','player',NULL),
('386','Alessandro Bastoni','Italy','Italy','player',NULL),
('387','Giorgio Scalvini','Italy','Italy','player',NULL),
('388','Riccardo Calafiori','Italy','Italy','player',NULL),
('389','Federico Dimarco','Italy','Italy','player',NULL),
('390','Nicolo Barella','Italy','Italy','player',NULL),
('391','Sandro Tonali','Italy','Italy','player',NULL),
('392','Bryan Cristante','Italy','Italy','player',NULL),
('393','Lorenzo Pellegrini','Italy','Italy','player',NULL),
('394','Federico Chiesa','Italy','Italy','player',NULL),
('395','Khvicha Kvaratskhelia','Italy','Italy','player',NULL),
('396','Giacomo Raspadori','Italy','Italy','player',NULL),
('397','Leonardo Bonucci','Italy','Italy','player',NULL),
('398','Moise Kean','Italy','Italy','player',NULL),
('399','Escudo Oficial','Ivory Coast','Ivory Coast','badge',NULL),
('400','Foto del Equipo','Ivory Coast','Ivory Coast','logo',NULL),
('401','Yahia Fofana','Ivory Coast','Ivory Coast','player',NULL),
('402','Badra Ali Sangaré','Ivory Coast','Ivory Coast','player',NULL),
('403','Ghislain Konan','Ivory Coast','Ivory Coast','player',NULL),
('404','Odilon Kossounou','Ivory Coast','Ivory Coast','player',NULL),
('405','Evan Ndicka','Ivory Coast','Ivory Coast','player',NULL),
('406','Serge Aurier','Ivory Coast','Ivory Coast','player',NULL),
('407','Wilfried Singo','Ivory Coast','Ivory Coast','player',NULL),
('408','Ibrahim Sangaré','Ivory Coast','Ivory Coast','player',NULL),
('409','Franck Kessié','Ivory Coast','Ivory Coast','player',NULL),
('410','Jean-Philippe Gbamin','Ivory Coast','Ivory Coast','player',NULL),
('411','Nicolas Pépé','Ivory Coast','Ivory Coast','player',NULL),
('412','Maxwell Cornet','Ivory Coast','Ivory Coast','player',NULL),
('413','Simon Adingra','Ivory Coast','Ivory Coast','player',NULL),
('414','Lazare Amani','Ivory Coast','Ivory Coast','player',NULL),
('415','Sébastien Haller','Ivory Coast','Ivory Coast','player',NULL),
('416','Oumar Diakité','Ivory Coast','Ivory Coast','player',NULL),
('417','Escudo Oficial','Jamaica','Jamaica','badge',NULL),
('418','Foto del Equipo','Jamaica','Jamaica','logo',NULL),
('419','Andre Blake','Jamaica','Jamaica','player',NULL),
('420','Dillon Barnes','Jamaica','Jamaica','player',NULL),
('421','Wes Morgan','Jamaica','Jamaica','player',NULL),
('422','Liam Moore','Jamaica','Jamaica','player',NULL),
('423','Kemar Lawrence','Jamaica','Jamaica','player',NULL),
('424','Miles Welch-Hayes','Jamaica','Jamaica','player',NULL),
('425','Oniel Fisher','Jamaica','Jamaica','player',NULL),
('426','Damion Lowe','Jamaica','Jamaica','player',NULL),
('427','Daniel Johnson','Jamaica','Jamaica','player',NULL),
('428','Je-Vaughn Watson','Jamaica','Jamaica','player',NULL),
('429','Ravel Morrison','Jamaica','Jamaica','player',NULL),
('430','Bobby Decordova-Reid','Jamaica','Jamaica','player',NULL),
('431','Shamar Nicholson','Jamaica','Jamaica','player',NULL),
('432','Leon Bailey','Jamaica','Jamaica','player',NULL),
('433','Michail Antonio','Jamaica','Jamaica','player',NULL),
('434','Bobby Reid','Jamaica','Jamaica','player',NULL),
('435','Escudo Oficial','Japan','Japan','badge',NULL),
('436','Foto del Equipo','Japan','Japan','logo',NULL),
('437','Zion Suzuki','Japan','Japan','player',NULL),
('438','Shuichi Gonda','Japan','Japan','player',NULL),
('439','Tsuyoshi Watanabe','Japan','Japan','player',NULL),
('440','Ko Itakura','Japan','Japan','player',NULL),
('441','Maya Yoshida','Japan','Japan','player',NULL),
('442','Yuto Nagatomo','Japan','Japan','player',NULL),
('443','Kaishu Sano','Japan','Japan','player',NULL),
('444','Daichi Kamada','Japan','Japan','player',NULL),
('445','Ritsu Doan','Japan','Japan','player',NULL),
('446','Takumi Minamino','Japan','Japan','player',NULL),
('447','Junya Ito','Japan','Japan','player',NULL),
('448','Kaoru Mitoma','Japan','Japan','player',NULL),
('449','Keito Nakamura','Japan','Japan','player',NULL),
('450','Takefusa Kubo','Japan','Japan','player',NULL),
('451','Shuto Machino','Japan','Japan','player',NULL),
('452','Ayase Ueda','Japan','Japan','player',NULL),
('453','Escudo Oficial','Jordan','Jordan','badge',NULL),
('454','Foto del Equipo','Jordan','Jordan','logo',NULL),
('455','Amer Shafi','Jordan','Jordan','player',NULL),
('456','Khaled Shehadeh','Jordan','Jordan','player',NULL),
('457','Mohammed Abu Hashish','Jordan','Jordan','player',NULL),
('458','Yazan Al-Arab','Jordan','Jordan','player',NULL),
('459','Abdallah Nasib','Jordan','Jordan','player',NULL),
('460','Baha Faisal','Jordan','Jordan','player',NULL),
('461','Ibrahim Saadeh','Jordan','Jordan','player',NULL),
('462','Nizar Al-Rashdan','Jordan','Jordan','player',NULL),
('463','Ahmad Al-Sarour','Jordan','Jordan','player',NULL),
('464','Noor Al-Rawabdeh','Jordan','Jordan','player',NULL),
('465','Mahmoud Al-Mardi','Jordan','Jordan','player',NULL),
('466','Ali Olwan','Jordan','Jordan','player',NULL),
('467','Abdullah Nasib','Jordan','Jordan','player',NULL),
('468','Yazeed Abulaila','Jordan','Jordan','player',NULL),
('469','Musa Al-Taamari','Jordan','Jordan','player',NULL),
('470','Yazan Al-Naimat','Jordan','Jordan','player',NULL),
('471','Escudo Oficial','Korea Republic','Korea Republic','badge',NULL),
('472','Foto del Equipo','Korea Republic','Korea Republic','logo',NULL),
('473','Hyeonwoo Jo','Korea Republic','Korea Republic','player',NULL),
('474','Jo Hyeon-woo','Korea Republic','Korea Republic','player',NULL),
('475','Min-Jae Kim','Korea Republic','Korea Republic','player',NULL),
('476','Kim Tae-hwan','Korea Republic','Korea Republic','player',NULL),
('477','Lee Ki-je','Korea Republic','Korea Republic','player',NULL),
('478','Kim Jin-su','Korea Republic','Korea Republic','player',NULL),
('479','Young-Gwol Seol','Korea Republic','Korea Republic','player',NULL),
('480','Taesook Lee','Korea Republic','Korea Republic','player',NULL),
('481','In-Beom Hwang','Korea Republic','Korea Republic','player',NULL),
('482','Jae-Sung Lee','Korea Republic','Korea Republic','player',NULL),
('483','Kangin Lee','Korea Republic','Korea Republic','player',NULL),
('484','Yumin Cho','Korea Republic','Korea Republic','player',NULL),
('485','Hee-Chan Hwang','Korea Republic','Korea Republic','player',NULL),
('486','Hyeongyu Oh','Korea Republic','Korea Republic','player',NULL),
('487','Cho Gue-sung','Korea Republic','Korea Republic','player',NULL),
('488','Son Heung-min','Korea Republic','Korea Republic','player',NULL),
('489','Escudo Oficial','Mexico','Mexico','badge',NULL),
('490','Foto del Equipo','Mexico','Mexico','logo',NULL),
('491','Luis Malagón','Mexico','Mexico','player',NULL),
('492','Guillermo Ochoa','Mexico','Mexico','player',NULL),
('493','Israel Reyes','Mexico','Mexico','player',NULL),
('494','Néstor Araujo','Mexico','Mexico','player',NULL),
('495','César Montes','Mexico','Mexico','player',NULL),
('496','Juan Vásquez','Mexico','Mexico','player',NULL),
('497','Gerardo Arteaga','Mexico','Mexico','player',NULL),
('498','Jesús Gallardo','Mexico','Mexico','player',NULL),
('499','Edson Álvarez','Mexico','Mexico','player',NULL),
('500','Carlos Rodríguez','Mexico','Mexico','player',NULL),
('501','Orbelín Pineda','Mexico','Mexico','player',NULL),
('502','Roberto Alvarado','Mexico','Mexico','player',NULL),
('503','Hirving Lozano','Mexico','Mexico','player',NULL),
('504','Henry Martín','Mexico','Mexico','player',NULL),
('505','Raúl Jiménez','Mexico','Mexico','player',NULL),
('506','Santiago Giménez','Mexico','Mexico','player',NULL),
('507','Escudo Oficial','Morocco','Morocco','badge',NULL),
('508','Foto del Equipo','Morocco','Morocco','logo',NULL),
('509','Yassine Bounou','Morocco','Morocco','player',NULL),
('510','Munir El Haddadi','Morocco','Morocco','player',NULL),
('511','Noussair Mazraoui','Morocco','Morocco','player',NULL),
('512','Nayef Aguerd','Morocco','Morocco','player',NULL),
('513','Romain Saïss','Morocco','Morocco','player',NULL),
('514','Achraf Hakimi','Morocco','Morocco','player',NULL),
('515','Sofyan Amrabat','Morocco','Morocco','player',NULL),
('516','Eliesse Ben Seghir','Morocco','Morocco','player',NULL),
('517','Ismael Saibari','Morocco','Morocco','player',NULL),
('518','Zakaria Aboukhlal','Morocco','Morocco','player',NULL),
('519','Selim Amallah','Morocco','Morocco','player',NULL),
('520','Amine Harit','Morocco','Morocco','player',NULL),
('521','Brahim Díaz','Morocco','Morocco','player',NULL),
('522','Abde Ezzalzouli','Morocco','Morocco','player',NULL),
('523','Ayoub El Kaabi','Morocco','Morocco','player',NULL),
('524','Youssef En-Nesyri','Morocco','Morocco','player',NULL),
('525','Escudo Oficial','Netherlands','Netherlands','badge',NULL),
('526','Foto del Equipo','Netherlands','Netherlands','logo',NULL),
('527','Bart Verbruggen','Netherlands','Netherlands','player',NULL),
('528','Mark Flekken','Netherlands','Netherlands','player',NULL),
('529','Virgil van Dijk','Netherlands','Netherlands','player',NULL),
('530','Stefan de Vrij','Netherlands','Netherlands','player',NULL),
('531','Matthijs de Ligt','Netherlands','Netherlands','player',NULL),
('532','Nathan Aké','Netherlands','Netherlands','player',NULL),
('533','Jeremie Frimpong','Netherlands','Netherlands','player',NULL),
('534','Denzel Dumfries','Netherlands','Netherlands','player',NULL),
('535','Tijjani Reijnders','Netherlands','Netherlands','player',NULL),
('536','Ryan Gravenberch','Netherlands','Netherlands','player',NULL),
('537','Xavi Simons','Netherlands','Netherlands','player',NULL),
('538','Cody Gakpo','Netherlands','Netherlands','player',NULL),
('539','Donyell Malen','Netherlands','Netherlands','player',NULL),
('540','Memphis Depay','Netherlands','Netherlands','player',NULL),
('541','Brian Brobbey','Netherlands','Netherlands','player',NULL),
('542','Wout Weghorst','Netherlands','Netherlands','player',NULL),
('543','Escudo Oficial','New Zealand','New Zealand','badge',NULL),
('544','Foto del Equipo','New Zealand','New Zealand','logo',NULL),
('545','Max Crocombe','New Zealand','New Zealand','player',NULL),
('546','Michael Woud','New Zealand','New Zealand','player',NULL),
('547','Liberato Cacace','New Zealand','New Zealand','player',NULL),
('548','Tommy Smith','New Zealand','New Zealand','player',NULL),
('549','Nando Pijnaker','New Zealand','New Zealand','player',NULL),
('550','Tim Payne','New Zealand','New Zealand','player',NULL),
('551','Finn Surman','New Zealand','New Zealand','player',NULL),
('552','Joe Bell','New Zealand','New Zealand','player',NULL),
('553','Sarpreet Singh','New Zealand','New Zealand','player',NULL),
('554','Matt Garbett','New Zealand','New Zealand','player',NULL),
('555','Clayton Lewis','New Zealand','New Zealand','player',NULL),
('556','Callan Elliot','New Zealand','New Zealand','player',NULL),
('557','Marko Stamenic','New Zealand','New Zealand','player',NULL),
('558','Elijah Just','New Zealand','New Zealand','player',NULL),
('559','Kosta Barbarouses','New Zealand','New Zealand','player',NULL),
('560','Chris Wood','New Zealand','New Zealand','player',NULL),
('561','Escudo Oficial','Norway','Norway','badge',NULL),
('562','Foto del Equipo','Norway','Norway','logo',NULL),
('563','Ørjan Nyland','Norway','Norway','player',NULL),
('564','Stian Rode Gregersen','Norway','Norway','player',NULL),
('565','Julian Ryerson','Norway','Norway','player',NULL),
('566','Christoffer Ajer','Norway','Norway','player',NULL),
('567','David Møller Wolfe','Norway','Norway','player',NULL),
('568','Sander Berge','Norway','Norway','player',NULL),
('569','Patrick Berg','Norway','Norway','player',NULL),
('570','Martin Ødegaard','Norway','Norway','player',NULL),
('571','Kristian Thorstvedt','Norway','Norway','player',NULL),
('572','Jens Petter Hauge','Norway','Norway','player',NULL),
('573','Mohamed Elyounoussi','Norway','Norway','player',NULL),
('574','Antonio Nusa','Norway','Norway','player',NULL),
('575','Oscar Bobb','Norway','Norway','player',NULL),
('576','Alexander Sørloth','Norway','Norway','player',NULL),
('577','Erling Haaland','Norway','Norway','player',NULL),
('578','Ola Solbakken','Norway','Norway','player',NULL),
('579','Escudo Oficial','Panama','Panama','badge',NULL),
('580','Foto del Equipo','Panama','Panama','logo',NULL),
('581','Orlando Mosquera','Panama','Panama','player',NULL),
('582','Luis Mejía','Panama','Panama','player',NULL),
('583','Andrés Andrade','Panama','Panama','player',NULL),
('584','Fidel Escobar','Panama','Panama','player',NULL),
('585','Roderick Miller','Panama','Panama','player',NULL),
('586','Michael Amir Murillo','Panama','Panama','player',NULL),
('587','Cristian Martínez','Panama','Panama','player',NULL),
('588','Adalberto Carrasquilla','Panama','Panama','player',NULL),
('589','Aníbal Godoy','Panama','Panama','player',NULL),
('590','César Yanis','Panama','Panama','player',NULL),
('591','Edgar Bárcenas','Panama','Panama','player',NULL),
('592','Alberto Quintero','Panama','Panama','player',NULL),
('593','José Fajardo','Panama','Panama','player',NULL),
('594','Ismael Díaz','Panama','Panama','player',NULL),
('595','Cecilio Waterman','Panama','Panama','player',NULL),
('596','José Luis Rodríguez','Panama','Panama','player',NULL),
('597','Escudo Oficial','Paraguay','Paraguay','badge',NULL),
('598','Foto del Equipo','Paraguay','Paraguay','logo',NULL),
('599','Antony Silva','Paraguay','Paraguay','player',NULL),
('600','Roberto Fernández','Paraguay','Paraguay','player',NULL),
('601','Gustavo Gómez','Paraguay','Paraguay','player',NULL),
('602','Omar Alderete','Paraguay','Paraguay','player',NULL),
('603','Júnior Alonso','Paraguay','Paraguay','player',NULL),
('604','Juan José Cáceres','Paraguay','Paraguay','player',NULL),
('605','Braian Ojeda','Paraguay','Paraguay','player',NULL),
('606','Richard Sánchez','Paraguay','Paraguay','player',NULL),
('607','Andrés Cubas','Paraguay','Paraguay','player',NULL),
('608','Mathías Villasanti','Paraguay','Paraguay','player',NULL),
('609','Julián Almirón','Paraguay','Paraguay','player',NULL),
('610','Miguel Almirón','Paraguay','Paraguay','player',NULL),
('611','Julio Enciso','Paraguay','Paraguay','player',NULL),
('612','Ramón Sosa','Paraguay','Paraguay','player',NULL),
('613','Darío Lezcano','Paraguay','Paraguay','player',NULL),
('614','Antonio Sanabria','Paraguay','Paraguay','player',NULL),
('615','Escudo Oficial','Poland','Poland','badge',NULL),
('616','Foto del Equipo','Poland','Poland','logo',NULL),
('617','Wojciech Szczęsny','Poland','Poland','player',NULL),
('618','Łukasz Fabiański','Poland','Poland','player',NULL),
('619','Jan Bednarek','Poland','Poland','player',NULL),
('620','Kamil Glik','Poland','Poland','player',NULL),
('621','Bartosz Bereszyński','Poland','Poland','player',NULL),
('622','Jakub Kiwior','Poland','Poland','player',NULL),
('623','Matty Cash','Poland','Poland','player',NULL),
('624','Mateusz Klich','Poland','Poland','player',NULL),
('625','Grzegorz Krychowiak','Poland','Poland','player',NULL),
('626','Piotr Zieliński','Poland','Poland','player',NULL),
('627','Przemysław Frankowski','Poland','Poland','player',NULL),
('628','Sebastian Szymański','Poland','Poland','player',NULL),
('629','Szymon Żurkowski','Poland','Poland','player',NULL),
('630','Michał Skóraś','Poland','Poland','player',NULL),
('631','Arkadiusz Milik','Poland','Poland','player',NULL),
('632','Robert Lewandowski','Poland','Poland','player',NULL),
('633','Escudo Oficial','Portugal','Portugal','badge',NULL),
('634','Foto del Equipo','Portugal','Portugal','logo',NULL),
('635','Diogo Costa','Portugal','Portugal','player',NULL),
('636','Rui Patrício','Portugal','Portugal','player',NULL),
('637','Rúben Dias','Portugal','Portugal','player',NULL),
('638','Pepe','Portugal','Portugal','player',NULL),
('639','João Cancelo','Portugal','Portugal','player',NULL),
('640','Nuno Mendes','Portugal','Portugal','player',NULL),
('641','João Neves','Portugal','Portugal','player',NULL),
('642','Vitinha','Portugal','Portugal','player',NULL),
('643','Bruno Fernandes','Portugal','Portugal','player',NULL),
('644','Rúben Neves','Portugal','Portugal','player',NULL),
('645','Bernardo Silva','Portugal','Portugal','player',NULL),
('646','Francisco Conceição','Portugal','Portugal','player',NULL),
('647','Pedro Neto','Portugal','Portugal','player',NULL),
('648','Rafael Leão','Portugal','Portugal','player',NULL),
('649','Gonçalo Ramos','Portugal','Portugal','player',NULL),
('650','Cristiano Ronaldo','Portugal','Portugal','player',NULL),
('651','Escudo Oficial','Qatar','Qatar','badge',NULL),
('652','Foto del Equipo','Qatar','Qatar','logo',NULL),
('653','Meshaal Barsham','Qatar','Qatar','player',NULL),
('654','Saad Al-Sheeb','Qatar','Qatar','player',NULL),
('655','Boualem Khoukhi','Qatar','Qatar','player',NULL),
('656','Abdelkarim Hassan','Qatar','Qatar','player',NULL),
('657','Lucas Mendes','Qatar','Qatar','player',NULL),
('658','Pedro Miguel','Qatar','Qatar','player',NULL),
('659','Bassam Al-Rawi','Qatar','Qatar','player',NULL),
('660','Homam Al-Amin','Qatar','Qatar','player',NULL),
('661','Ahmed Fathi','Qatar','Qatar','player',NULL),
('662','Karim Boudiaf','Qatar','Qatar','player',NULL),
('663','Edmilson Junior','Qatar','Qatar','player',NULL),
('664','Hassan Al-Haydos','Qatar','Qatar','player',NULL),
('665','Ahmed Al-Qaeni','Qatar','Qatar','player',NULL),
('666','Akram Hassan Afif','Qatar','Qatar','player',NULL),
('667','Almoez Ali','Qatar','Qatar','player',NULL),
('668','Yusuf Abdurisag','Qatar','Qatar','player',NULL),
('669','Escudo Oficial','Saudi Arabia','Saudi Arabia','badge',NULL),
('670','Foto del Equipo','Saudi Arabia','Saudi Arabia','logo',NULL),
('671','Mohammed Al-Owais','Saudi Arabia','Saudi Arabia','player',NULL),
('672','Nawaf Al-Aqidi','Saudi Arabia','Saudi Arabia','player',NULL),
('673','Hassan Altambakti','Saudi Arabia','Saudi Arabia','player',NULL),
('674','Saud Abdulhamid','Saudi Arabia','Saudi Arabia','player',NULL),
('675','Ali Al-Bulaihi','Saudi Arabia','Saudi Arabia','player',NULL),
('676','Jehad Thikri','Saudi Arabia','Saudi Arabia','player',NULL),
('677','Abdulelah Al-Malki','Saudi Arabia','Saudi Arabia','player',NULL),
('678','Nasser Al-Dawsari','Saudi Arabia','Saudi Arabia','player',NULL),
('679','Abdullah Alkhanbari','Saudi Arabia','Saudi Arabia','player',NULL),
('680','Musar Al-Juwayr','Saudi Arabia','Saudi Arabia','player',NULL),
('681','Faisal Al-Ghamdi','Saudi Arabia','Saudi Arabia','player',NULL),
('682','Salem Al-Dawsari','Saudi Arabia','Saudi Arabia','player',NULL),
('683','Feras Al-Brikan','Saudi Arabia','Saudi Arabia','player',NULL),
('684','Abdullah Al-Hamdan','Saudi Arabia','Saudi Arabia','player',NULL),
('685','Saleh Al-Bashir','Saudi Arabia','Saudi Arabia','player',NULL),
('686','Saleh Al-Shehri','Saudi Arabia','Saudi Arabia','player',NULL),
('687','Escudo Oficial','Scotland','Scotland','badge',NULL),
('688','Foto del Equipo','Scotland','Scotland','logo',NULL),
('689','Angus Gunn','Scotland','Scotland','player',NULL),
('690','Craig Gordon','Scotland','Scotland','player',NULL),
('691','Kieran Tierney','Scotland','Scotland','player',NULL),
('692','Grant Hanley','Scotland','Scotland','player',NULL),
('693','Jack Hendry','Scotland','Scotland','player',NULL),
('694','Anthony Ralston','Scotland','Scotland','player',NULL),
('695','Andrew Robertson','Scotland','Scotland','player',NULL),
('696','Scott McTominay','Scotland','Scotland','player',NULL),
('697','Billy Gilmour','Scotland','Scotland','player',NULL),
('698','Lewis Ferguson','Scotland','Scotland','player',NULL),
('699','Kenny McLean','Scotland','Scotland','player',NULL),
('700','Ryan Christie','Scotland','Scotland','player',NULL),
('701','John McGinn','Scotland','Scotland','player',NULL),
('702','Ben Doak','Scotland','Scotland','player',NULL),
('703','Lawrence Shankland','Scotland','Scotland','player',NULL),
('704','Ché Adams','Scotland','Scotland','player',NULL),
('705','Escudo Oficial','Senegal','Senegal','badge',NULL),
('706','Foto del Equipo','Senegal','Senegal','logo',NULL),
('707','Édouard Mendy','Senegal','Senegal','player',NULL),
('708','Alfred Gomis','Senegal','Senegal','player',NULL),
('709','Kalidou Koulibaly','Senegal','Senegal','player',NULL),
('710','Moussa Niakhaté','Senegal','Senegal','player',NULL),
('711','Formose Mendy','Senegal','Senegal','player',NULL),
('712','El Hadji Malick Diouf','Senegal','Senegal','player',NULL),
('713','Pape Guèye','Senegal','Senegal','player',NULL),
('714','Idrissa Gana Gueye','Senegal','Senegal','player',NULL),
('715','Pape Matar Sarr','Senegal','Senegal','player',NULL),
('716','Lamine Camara','Senegal','Senegal','player',NULL),
('717','Krepin Diatta','Senegal','Senegal','player',NULL),
('718','Ismaïla Sarr','Senegal','Senegal','player',NULL),
('719','Habib Diallo','Senegal','Senegal','player',NULL),
('720','Bamba Dieng','Senegal','Senegal','player',NULL),
('721','Nicolas Jackson','Senegal','Senegal','player',NULL),
('722','Sadio Mané','Senegal','Senegal','player',NULL),
('723','Escudo Oficial','South Africa','South Africa','badge',NULL),
('724','Foto del Equipo','South Africa','South Africa','logo',NULL),
('725','Ronwen Williams','South Africa','South Africa','player',NULL),
('726','Veli Mothwa','South Africa','South Africa','player',NULL),
('727','Siyabonga Ngezana','South Africa','South Africa','player',NULL),
('728','Siyanda Xulu','South Africa','South Africa','player',NULL),
('729','Aubrey Modiba','South Africa','South Africa','player',NULL),
('730','Terrence Mashego','South Africa','South Africa','player',NULL),
('731','Khuliso Mudau','South Africa','South Africa','player',NULL),
('732','Teboho Mokoena','South Africa','South Africa','player',NULL),
('733','Bongani Zungu','South Africa','South Africa','player',NULL),
('734','Yaya Sithole','South Africa','South Africa','player',NULL),
('735','Mbekezeli Mbokazi','South Africa','South Africa','player',NULL),
('736','Themba Zwane','South Africa','South Africa','player',NULL),
('737','Percy Tau','South Africa','South Africa','player',NULL),
('738','Oswin Appollis','South Africa','South Africa','player',NULL),
('739','Evidence Makgopa','South Africa','South Africa','player',NULL),
('740','Lyle Foster','South Africa','South Africa','player',NULL),
('741','Escudo Oficial','Spain','Spain','badge',NULL),
('742','Foto del Equipo','Spain','Spain','logo',NULL),
('743','Unai Simón','Spain','Spain','player',NULL),
('744','Alejandro Remiro','Spain','Spain','player',NULL),
('745','Robin Le Normand','Spain','Spain','player',NULL),
('746','Dean Huijsen','Spain','Spain','player',NULL),
('747','Aymeric Laporte','Spain','Spain','player',NULL),
('748','César Azpilicueta','Spain','Spain','player',NULL),
('749','Marc Cucurella','Spain','Spain','player',NULL),
('750','Martín Zubimendi','Spain','Spain','player',NULL),
('751','Rodri','Spain','Spain','player',NULL),
('752','Gavi','Spain','Spain','player',NULL),
('753','Pedri','Spain','Spain','player',NULL),
('754','Fabián Ruiz','Spain','Spain','player',NULL),
('755','Lamine Yamal','Spain','Spain','player',NULL),
('756','Nico Williams','Spain','Spain','player',NULL),
('757','Álvaro Morata','Spain','Spain','player',NULL),
('758','Mikel Oyarzabal','Spain','Spain','player',NULL),
('759','Escudo Oficial','Sweden','Sweden','badge',NULL),
('760','Foto del Equipo','Sweden','Sweden','logo',NULL),
('761','Robin Olsen','Sweden','Sweden','player',NULL),
('762','Karl-Johan Johnsson','Sweden','Sweden','player',NULL),
('763','Victor Lindelöf','Sweden','Sweden','player',NULL),
('764','Mikael Lustig','Sweden','Sweden','player',NULL),
('765','Sebastian Larsson','Sweden','Sweden','player',NULL),
('766','Jens Cajuste','Sweden','Sweden','player',NULL),
('767','Filip Helander','Sweden','Sweden','player',NULL),
('768','Emil Forsberg','Sweden','Sweden','player',NULL),
('769','Mattias Svanberg','Sweden','Sweden','player',NULL),
('770','Dejan Kulusevski','Sweden','Sweden','player',NULL),
('771','Anthony Elanga','Sweden','Sweden','player',NULL),
('772','Jordan Larsson','Sweden','Sweden','player',NULL),
('773','Alexander Isak','Sweden','Sweden','player',NULL),
('774','Viktor Gyökeres','Sweden','Sweden','player',NULL),
('775','Isaac Kiese Thelin','Sweden','Sweden','player',NULL),
('776','Zlatan Ibrahimović','Sweden','Sweden','player',NULL),
('777','Escudo Oficial','Switzerland','Switzerland','badge',NULL),
('778','Foto del Equipo','Switzerland','Switzerland','logo',NULL),
('779','Gregor Kobel','Switzerland','Switzerland','player',NULL),
('780','Yann Sommer','Switzerland','Switzerland','player',NULL),
('781','Manuel Akanji','Switzerland','Switzerland','player',NULL),
('782','Fabian Schär','Switzerland','Switzerland','player',NULL),
('783','Nico Elvedi','Switzerland','Switzerland','player',NULL),
('784','Kevin Mbabu','Switzerland','Switzerland','player',NULL),
('785','Ricardo Rodríguez','Switzerland','Switzerland','player',NULL),
('786','Granit Xhaka','Switzerland','Switzerland','player',NULL),
('787','Denis Zakaria','Switzerland','Switzerland','player',NULL),
('788','Remo Freuler','Switzerland','Switzerland','player',NULL),
('789','Manuel Widmer','Switzerland','Switzerland','player',NULL),
('790','Dan Ndoye','Switzerland','Switzerland','player',NULL),
('791','Rubén Vargas','Switzerland','Switzerland','player',NULL),
('792','Noah Okafor','Switzerland','Switzerland','player',NULL),
('793','Zeki Amdouni','Switzerland','Switzerland','player',NULL),
('794','Breel Embolo','Switzerland','Switzerland','player',NULL),
('795','Escudo Oficial','Tunisia','Tunisia','badge',NULL),
('796','Foto del Equipo','Tunisia','Tunisia','logo',NULL),
('797','Aymen Dahmen','Tunisia','Tunisia','player',NULL),
('798','Bechir Ben Said','Tunisia','Tunisia','player',NULL),
('799','Montassar Talbi','Tunisia','Tunisia','player',NULL),
('800','Yassin Meriah','Tunisia','Tunisia','player',NULL),
('801','Mohamed Dräger','Tunisia','Tunisia','player',NULL),
('802','Ali Abdi','Tunisia','Tunisia','player',NULL),
('803','Wajdi Kechrida','Tunisia','Tunisia','player',NULL),
('804','Ferjani Sassi','Tunisia','Tunisia','player',NULL),
('805','Aïssa Laïdouni','Tunisia','Tunisia','player',NULL),
('806','Ellyes Skhiri','Tunisia','Tunisia','player',NULL),
('807','Hannibal Mejbri','Tunisia','Tunisia','player',NULL),
('808','Naïm Sliti','Tunisia','Tunisia','player',NULL),
('809','Wahbi Khazri','Tunisia','Tunisia','player',NULL),
('810','Elias Achouri','Tunisia','Tunisia','player',NULL),
('811','Seifeddine Jaziri','Tunisia','Tunisia','player',NULL),
('812','Hazem Mastouri','Tunisia','Tunisia','player',NULL),
('813','Escudo Oficial','Turkey','Turkey','badge',NULL),
('814','Foto del Equipo','Turkey','Turkey','logo',NULL),
('815','Mert Günok','Turkey','Turkey','player',NULL),
('816','Altay Bayındır','Turkey','Turkey','player',NULL),
('817','Çağlar Söyüncü','Turkey','Turkey','player',NULL),
('818','Merih Demiral','Turkey','Turkey','player',NULL),
('819','Samet Akaydın','Turkey','Turkey','player',NULL),
('820','Zeki Çelik','Turkey','Turkey','player',NULL),
('821','Ferdi Kadıoğlu','Turkey','Turkey','player',NULL),
('822','Hakan Çalhanoğlu','Turkey','Turkey','player',NULL),
('823','Salih Özcan','Turkey','Turkey','player',NULL),
('824','Arda Güler','Turkey','Turkey','player',NULL),
('825','Kenan Yıldız','Turkey','Turkey','player',NULL),
('826','Baris Alper Yılmaz','Turkey','Turkey','player',NULL),
('827','Kerem Aktürkoğlu','Turkey','Turkey','player',NULL),
('828','Muhammed Şengezer','Turkey','Turkey','player',NULL),
('829','Cenk Tosun','Turkey','Turkey','player',NULL),
('830','Burak Yılmaz','Turkey','Turkey','player',NULL),
('831','Escudo Oficial','United States','United States','badge',NULL),
('832','Foto del Equipo','United States','United States','logo',NULL),
('833','Matt Freese','United States','United States','player',NULL),
('834','Zack Steffen','United States','United States','player',NULL),
('835','Chris Richards','United States','United States','player',NULL),
('836','Miles Robinson','United States','United States','player',NULL),
('837','Tim Ream','United States','United States','player',NULL),
('838','Sergino Dest','United States','United States','player',NULL),
('839','Antonee Robinson','United States','United States','player',NULL),
('840','Tyler Adams','United States','United States','player',NULL),
('841','Weston McKennie','United States','United States','player',NULL),
('842','Tanner Tessmann','United States','United States','player',NULL),
('843','Giovanni Reyna','United States','United States','player',NULL),
('844','Timothy Weah','United States','United States','player',NULL),
('845','Malik Tillman','United States','United States','player',NULL),
('846','Folarin Balogun','United States','United States','player',NULL),
('847','Ricardo Pepi','United States','United States','player',NULL),
('848','Christian Pulisic','United States','United States','player',NULL),
('849','Escudo Oficial','Uruguay','Uruguay','badge',NULL),
('850','Foto del Equipo','Uruguay','Uruguay','logo',NULL),
('851','Sergio Rochet','Uruguay','Uruguay','player',NULL),
('852','Guillermo Varela','Uruguay','Uruguay','player',NULL),
('853','Ronald Araújo','Uruguay','Uruguay','player',NULL),
('854','José María Giménez','Uruguay','Uruguay','player',NULL),
('855','Sebastián Cáceres','Uruguay','Uruguay','player',NULL),
('856','Martín Cáceres','Uruguay','Uruguay','player',NULL),
('857','Mathías Olivera','Uruguay','Uruguay','player',NULL),
('858','Nahitan Nández','Uruguay','Uruguay','player',NULL),
('859','Rodrigo Bentancur','Uruguay','Uruguay','player',NULL),
('860','Manuel Ugarte','Uruguay','Uruguay','player',NULL),
('861','Lucas Torreira','Uruguay','Uruguay','player',NULL),
('862','Federico Valverde','Uruguay','Uruguay','player',NULL),
('863','Giorgian De Arrascaeta','Uruguay','Uruguay','player',NULL),
('864','Facundo Pellistri','Uruguay','Uruguay','player',NULL),
('865','Darwin Núñez','Uruguay','Uruguay','player',NULL),
('866','Luis Suárez','Uruguay','Uruguay','player',NULL),
('867','Escudo Oficial','Uzbekistan','Uzbekistan','badge',NULL),
('868','Foto del Equipo','Uzbekistan','Uzbekistan','logo',NULL),
('869','Utkir Yusupov','Uzbekistan','Uzbekistan','player',NULL),
('870','Timur Kapadze','Uzbekistan','Uzbekistan','player',NULL),
('871','Abdukodir Khusanov','Uzbekistan','Uzbekistan','player',NULL),
('872','Farrukh Sayfiev','Uzbekistan','Uzbekistan','player',NULL),
('873','Sherzod Nasrullaev','Uzbekistan','Uzbekistan','player',NULL),
('874','Rustam Ashurmatov','Uzbekistan','Uzbekistan','player',NULL),
('875','Khushnudbek Aliqulov','Uzbekistan','Uzbekistan','player',NULL),
('876','Khokjabkar Alijonov','Uzbekistan','Uzbekistan','player',NULL),
('877','Dostonbek Khamdamov','Uzbekistan','Uzbekistan','player',NULL),
('878','Javokhir Sidiqov','Uzbekistan','Uzbekistan','player',NULL),
('879','Islom Tukhtakhujaev','Uzbekistan','Uzbekistan','player',NULL),
('880','Bahodir Abdullaev','Uzbekistan','Uzbekistan','player',NULL),
('881','Odiljon Hamrobekov','Uzbekistan','Uzbekistan','player',NULL),
('882','Otabek Shukurov','Uzbekistan','Uzbekistan','player',NULL),
('883','Abbosbek Fayzullaev','Uzbekistan','Uzbekistan','player',NULL),
('884','Eldor Shomurodov','Uzbekistan','Uzbekistan','player',NULL),
('885','Emiliano Martínez','Mejores Porteros','Mejores Porteros','special',NULL),
('886','Thibaut Courtois','Mejores Porteros','Mejores Porteros','special',NULL),
('887','Alisson','Mejores Porteros','Mejores Porteros','special',NULL),
('888','Mike Maignan','Mejores Porteros','Mejores Porteros','special',NULL),
('889','Marc-André ter Stegen','Mejores Porteros','Mejores Porteros','special',NULL),
('890','Yassine Bounou','Mejores Porteros','Mejores Porteros','special',NULL),
('891','Diogo Costa','Mejores Porteros','Mejores Porteros','special',NULL),
('892','Unai Simón','Mejores Porteros','Mejores Porteros','special',NULL),
('893','Gregor Kobel','Mejores Porteros','Mejores Porteros','special',NULL),
('894','Jordan Pickford','Mejores Porteros','Mejores Porteros','special',NULL),
('895','Zion Suzuki','Mejores Porteros','Mejores Porteros','special',NULL),
('896','Ronwen Williams','Mejores Porteros','Mejores Porteros','special',NULL),
('897','Dayne St. Clair','Mejores Porteros','Mejores Porteros','special',NULL),
('898','Kasper Schmeichel','Mejores Porteros','Mejores Porteros','special',NULL),
('899','Gianluigi Donnarumma','Mejores Porteros','Mejores Porteros','special',NULL),
('900','Meshaal Barsham','Mejores Porteros','Mejores Porteros','special',NULL),
('901','Virgil van Dijk','Mejores Defensas','Mejores Defensas','special',NULL),
('902','Éder Militão','Mejores Defensas','Mejores Defensas','special',NULL),
('903','Joško Gvardiol','Mejores Defensas','Mejores Defensas','special',NULL),
('904','William Saliba','Mejores Defensas','Mejores Defensas','special',NULL),
('905','Antonio Rüdiger','Mejores Defensas','Mejores Defensas','special',NULL),
('906','Min-Jae Kim','Mejores Defensas','Mejores Defensas','special',NULL),
('907','Achraf Hakimi','Mejores Defensas','Mejores Defensas','special',NULL),
('908','Alphonso Davies','Mejores Defensas','Mejores Defensas','special',NULL),
('909','Nuno Mendes','Mejores Defensas','Mejores Defensas','special',NULL),
('910','Rúben Dias','Mejores Defensas','Mejores Defensas','special',NULL),
('911','Cristian Romero','Mejores Defensas','Mejores Defensas','special',NULL),
('912','Kalidou Koulibaly','Mejores Defensas','Mejores Defensas','special',NULL),
('913','Ronald Araújo','Mejores Defensas','Mejores Defensas','special',NULL),
('914','Dean Huijsen','Mejores Defensas','Mejores Defensas','special',NULL),
('915','Marquinhos','Mejores Defensas','Mejores Defensas','special',NULL),
('916','Alessandro Bastoni','Mejores Defensas','Mejores Defensas','special',NULL),
('917','Jude Bellingham','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('918','Luka Modrić','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('919','Kevin De Bruyne','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('920','Pedri','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('921','Rodri','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('922','Federico Valverde','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('923','Moisés Caicedo','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('924','Martin Ødegaard','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('925','Florian Wirtz','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('926','Sofyan Amrabat','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('927','Joshua Kimmich','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('928','Bruno Fernandes','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('929','Scott McTominay','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('930','Enzo Fernández','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('931','Tijjani Reijnders','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('932','Aurélien Tchouaméni','Mejores Mediocampistas','Mejores Mediocampistas','special',NULL),
('933','Erling Haaland','Mejores Delanteros','Mejores Delanteros','special',NULL),
('934','Kylian Mbappé','Mejores Delanteros','Mejores Delanteros','special',NULL),
('935','Harry Kane','Mejores Delanteros','Mejores Delanteros','special',NULL),
('936','Vinícius Júnior','Mejores Delanteros','Mejores Delanteros','special',NULL),
('937','Mohamed Salah','Mejores Delanteros','Mejores Delanteros','special',NULL),
('938','Lamine Yamal','Mejores Delanteros','Mejores Delanteros','special',NULL),
('939','Romelu Lukaku','Mejores Delanteros','Mejores Delanteros','special',NULL),
('940','Darwin Núñez','Mejores Delanteros','Mejores Delanteros','special',NULL),
('941','Raphinha','Mejores Delanteros','Mejores Delanteros','special',NULL),
('942','Jonathan David','Mejores Delanteros','Mejores Delanteros','special',NULL),
('943','Sadio Mané','Mejores Delanteros','Mejores Delanteros','special',NULL),
('944','Viktor Gyökeres','Mejores Delanteros','Mejores Delanteros','special',NULL),
('945','Alexander Sørloth','Mejores Delanteros','Mejores Delanteros','special',NULL),
('946','Luis Díaz','Mejores Delanteros','Mejores Delanteros','special',NULL),
('947','Santiago Giménez','Mejores Delanteros','Mejores Delanteros','special',NULL),
('948','Bukayo Saka','Mejores Delanteros','Mejores Delanteros','special',NULL),
('949','Lionel Messi','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('950','Cristiano Ronaldo','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('951','Kylian Mbappé','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('952','Harry Kane','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('953','Son Heung-min','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('954','Erling Haaland','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('955','Mohamed Salah','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('956','Lamine Yamal','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('957','Jude Bellingham','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('958','Kevin De Bruyne','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('959','Luka Modrić','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('960','Federico Valverde','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('961','Vinícius Júnior','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('962','Florian Wirtz','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('963','Pedri','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('964','Rodri','Estrellas del Torneo','Estrellas del Torneo','special',NULL),
('965','Zinedine Zidane','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('966','Ronaldo Nazário','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('967','Pelé','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('968','Diego Maradona','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('969','Ronaldinho','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('970','Thierry Henry','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('971','Oliver Kahn','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('972','Miroslav Klose','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('973','Roberto Baggio','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('974','Paolo Maldini','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('975','Cafu','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('976','Xavi Hernández','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('977','Andrés Iniesta','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('978','Johan Cruyff','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('979','Gerd Müller','Glorias Mundialistas','Glorias Mundialistas','special',NULL),
('980','Eusébio','Glorias Mundialistas','Glorias Mundialistas','special',NULL);